### ISSUE TITLE
ScreenMapControllers has menu elements sticking off the bottom

### ISSUE THREAD

**Issue by kyzentun** [dguzek/UPSRT#2]
I think it happens from using a taller font than the fallback theme.  Just change the LinesVisible metric.

[ScreenMapControllers]
LinesVisible=13
LockInputSecs=0
AutoDismissWarningSecs=.1

**Comment by dguzek** [comment]
Resolves as of [this commit](https://github.com/dguzek/UPSRT/commit/d8e0031ae7464526ca11346d346f3af1fcc83e04).  Thank you for finding this issue and providing a simple fix.
