### ISSUE TITLE
Cooler Than Blue issue

### ISSUE THREAD

**Issue by HeySora** [dguzek/UPSRT#3]
When launching the battle, nothing happens. With lua errors shown, this appears : https://files.heysora.net/img/0QKYefKl.png

After several restarts of Stepmania, this issue stays here :/

**Comment by dguzek** [comment]
The error that you've provided suggests that the `visible()` command is being called on a table on line 465 of *Cooler Than Blue/lua/default.lua*

That's a very confusing error to me.  Line 465 of that file doesn't call `visible()` so I'm quite perplexed by the error you're getting.  Are you attempting to play *Cooler Than Blue* in a normal theme or as part of the UPSRT theme?  What version of StepMania are you using?

Maybe try re-downloading the UPSRT pack of simfiles?

**Comment by HeySora** [comment]
In my default.lua, line 465 was calling _SCREENMAN:GetTopScreen():GetChild("Overlay"):visible(false);_

I re-downloaded the simfiles, and now it's working great. It's very weird...
